trigger:
- none
variables:
  - group: OrchestrationPipeline

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest' 
        steps:
          - checkout: self
            fetchDepth: 1
          - task: PythonScript@0
            inputs:
              scriptSource: 'filePath'
              scriptPath: 'orchestrator.py'
              arguments: '$(solution_type) $(PAT)'
              failOnStderr: true